#!/usr/bin/env python3
"""Convert the six user-selected local tracks to bounded, embedded IMA ADPCM.

Missing tracks are explicit empty slots in development. --require-all prevents
shipping that development image as a music-loaded build. No media is downloaded.
"""
from __future__ import annotations

import argparse
import array
import hashlib
import json
import math
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent
STEPS = (7,8,9,10,11,12,13,14,16,17,19,21,23,25,28,31,34,37,41,45,50,55,
         60,66,73,80,88,97,107,118,130,143,157,173,190,209,230,253,279,307,
         337,371,408,449,494,544,598,658,724,796,876,963,1060,1166,1282,1411,
         1552,1707,1878,2066,2272,2499,2749,3024,3327,3660,4026,4428,4871,
         5358,5894,6484,7132,7845,8630,9493,10442,11487,12635,13899,15289,
         16818,18500,20350,22385,24623,27086,29794,32767)
INDEX = (-1,-1,-1,-1,2,4,6,8)
MAX_AUDIO_BYTES = 5 * 1024 * 1024


def encode(samples):
    predictor = index = 0
    result = bytearray((len(samples) + 1) // 2)
    for i, sample in enumerate(samples):
        diff = int(sample) - predictor
        code = 8 if diff < 0 else 0
        diff = abs(diff)
        step = STEPS[index]
        change = step >> 3
        for bit, threshold in ((4, step), (2, step >> 1), (1, step >> 2)):
            if diff >= threshold:
                code |= bit
                diff -= threshold
                change += threshold
        predictor = max(-32768, min(32767, predictor + (-change if code & 8 else change)))
        index = max(0, min(88, index + INDEX[code & 7]))
        result[i // 2] |= code << ((i & 1) * 4)
    return bytes(result)


def read_manifest(path):
    manifest = json.loads(path.read_text())
    tracks = manifest.get("tracks", [])
    if manifest.get("sample_rate") != 16000 or len(tracks) != 6:
        raise ValueError("Expected six tracks and a 16000 Hz sample rate")
    for track in tracks:
        if not isinstance(track.get("title"), str) or not track["title"].strip():
            raise ValueError("Every track needs a nonempty title")
        if len(track["title"]) > 64:
            raise ValueError("Track title exceeds 64 characters")
        file = Path(track["file"])
        if file.is_absolute() or ".." in file.parts:
            raise ValueError("Audio file must be inside the manifest directory")
        for key in ("start", "duration"):
            val = track[key]
            if isinstance(val, bool) or not isinstance(val, (int, float)) or not math.isfinite(val):
                raise ValueError(f"Invalid {key}")
        if track["start"] < 0 or not 0.1 <= track["duration"] <= 120:
            raise ValueError("Start must be nonnegative; duration must be 0.1–120 seconds")
    return tracks


def pack(manifest_path, output, require_all=False):
    tracks = read_manifest(manifest_path)
    missing = [t["file"] for t in tracks if not (manifest_path.parent / t["file"]).is_file()]
    if missing and require_all:
        raise ValueError("Missing audio: " + ", ".join(missing))
    lines = ['/* Generated by tools/pack_bgm.py. Missing data is never fake music. */',
             '#include "bgm_tracks.h"', '']
    entries, report = [], []
    total_bytes = 0
    for i, track in enumerate(tracks):
        path = manifest_path.parent / track["file"]
        title = json.dumps(track["title"], ensure_ascii=False)
        if not path.is_file():
            entries.append(f'    {{{title}, NULL, 0, 0}},')
            report.append({"title": track["title"], "loaded": False})
            continue
        # Clamp peaks and add gentle boundaries; source selection stays explicit.
        fade_out = max(0, track["duration"] - 0.05)
        pcm = subprocess.run([
            "ffmpeg", "-nostdin", "-v", "error", "-ss", str(track["start"]),
            "-i", str(path), "-t", str(track["duration"]), "-vn", "-ac", "1",
            "-ar", "16000", "-af",
            f"alimiter=limit=0.8:level=false,afade=t=in:d=0.02,afade=t=out:st={fade_out}:d=0.05",
            "-f", "s16le", "pipe:1"], capture_output=True, check=True).stdout
        samples = array.array("h")
        samples.frombytes(pcm)
        if sys.byteorder != "little":
            samples.byteswap()
        if not samples:
            raise ValueError(f"{path.name}: clip is empty; check its start time")
        data = encode(samples)
        total_bytes += len(data)
        if total_bytes > MAX_AUDIO_BYTES:
            raise ValueError("Audio exceeds 5 MiB; shorten the configured clips")
        lines.append(f"static const uint8_t track_{i}[] = {{")
        for offset in range(0, len(data), 24):
            lines.append("    " + ",".join(f"0x{v:02x}" for v in data[offset:offset + 24]) + ",")
        lines.append("};\n")
        entries.append(f"    {{{title}, track_{i}, sizeof(track_{i}), {len(samples)}u}},")
        report.append({"title": track["title"], "loaded": True,
                       "source_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                       "encoded_sha256": hashlib.sha256(data).hexdigest(),
                       "samples": len(samples), "bytes": len(data),
                       "start": track["start"], "seconds": len(samples) / 16000})
    lines.extend(["const bgm_track_t bgm_tracks[BGM_TRACK_COUNT] = {", *entries, "};", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    temp = output.with_suffix(".tmp")
    temp.write_text("\n".join(lines))
    temp.replace(output)
    report_path = output.with_suffix(".json")
    report_path.write_text(json.dumps({"audio_bytes": total_bytes, "tracks": report},
                                     ensure_ascii=False, indent=2) + "\n")
    return report


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=ROOT / "assets/music/playlist.json")
    parser.add_argument("--output", type=Path, default=ROOT / "main/bgm_tracks_data.c")
    parser.add_argument("--require-all", action="store_true")
    args = parser.parse_args()
    try:
        report = pack(args.manifest, args.output, args.require_all)
    except (ValueError, OSError, subprocess.CalledProcessError) as exc:
        parser.exit(1, f"Audio pack failed: {exc}\n")
    print(f"Loaded {sum(t['loaded'] for t in report)}/6 tracks: {args.output}")
